[toolchain]
channel = "nightly-2025-12-20"
components = [
  "cargo",
  "rust-analyzer",
  "rust-src",
  "rustc-codegen-cranelift",
  "rustc-dev",
  "rustfmt",
]
profile = "default"
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "x86_64-pc-windows-gnu",
  # "wasm32-unknown-unknown",
]
